---
language: ruby
sudo: false
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake all"]
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  - PUPPET_VERSION=2.7.0
  - PUPPET_VERSION=3.5
  - PUPPET_VERSION=3.7
  - PUPPET_VERSION=3.7 FUTURE_PARSER="yes"
matrix:
  exclude:
    # No real support for Ruby 1.9.3 on Puppet 2.x
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.0
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.0
    # No support for Ruby 2.1 before Puppet 3.5
    - rvm: 2.1.5
      env: PUPPET_VERSION=2.7.0
